# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79ba489793776f3196c1ec87abd2cb618a17595a1389563a9e4af1c3a995d2114680b6d10e72ca6f002b31d6edd33dbbd4a4138de2fe0cd6e3d7f7b608693358

test:
  secret_key_base: 64d98dd22d5ea1e54b0decd5cec305b88241e21a8c415999cf225fe7d049b677daeb4b20c6da38e89b6567d383581c0e0e474c9c68b5556a847ca2e5cd61fd67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
